version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: enterprise
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app"]
      interval: 5s
      retries: 10
  redis:
    image: redis:7
    ports: ["6379:6379"]
  mailhog:
    image: mailhog/mailhog
    ports: ["8025:8025", "1025:1025"]